# Generated by Django 3.1.7 on 2021-07-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pojazd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=300)),
                ('rok_produkcji', models.IntegerField()),
                ('silnik', models.CharField(max_length=100)),
                ('rejstracja', models.CharField(max_length=100)),
                ('kolor', models.CharField(max_length=100)),
                ('data_zakupu', models.DateField()),
                ('data_sprzedazy', models.DateField(null=True)),
                ('kola', models.IntegerField()),
                ('historia', models.IntegerField()),
            ],
        ),
    ]
