# Generated by Django 3.1.7 on 2021-07-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pojazd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojazd',
            name='data_sprzedazy',
            field=models.DateField(blank=True, null=True),
        ),
    ]
