# Generated by Django 3.1.7 on 2021-07-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pojazd', '0002_auto_20210706_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='PojazdHistoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejstracja', models.CharField(max_length=100)),
                ('wydarzenie', models.CharField(max_length=200)),
                ('data_wydarzenia', models.DateField()),
                ('opis', models.TextField(max_length=10000)),
                ('zdjecie', models.FileField(blank=True, upload_to='')),
            ],
        ),
    ]
