# Generated by Django 3.1.7 on 2021-07-06 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pojazd', '0003_pojazdhistoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pojazd',
            old_name='rejstracja',
            new_name='rejestracja',
        ),
        migrations.RenameField(
            model_name='pojazdhistoria',
            old_name='rejstracja',
            new_name='rejestracja',
        ),
    ]
