# Generated by Django 3.1.7 on 2021-07-08 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pojazd', '0004_auto_20210706_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pojazd',
            name='kola',
        ),
    ]
