# Generated by Django 3.1.7 on 2021-07-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pojazd', '0005_remove_pojazd_kola'),
    ]

    operations = [
        migrations.CreateModel(
            name='PojazdKola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('opony', models.CharField(max_length=200)),
                ('felgi', models.CharField(max_length=200)),
                ('sruby', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='pojazd',
            name='kola',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=1000, null=True),
        ),
    ]
