# Generated by Django 3.1.7 on 2021-07-08 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pojazd', '0006_auto_20210708_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojazd',
            name='kola',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pojazd.pojazdkola'),
        ),
    ]
