# Generated by Django 3.1.7 on 2021-07-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pojazd', '0007_auto_20210708_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojazd',
            name='rejestracja',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
