# Generated by Django 3.1.7 on 2021-07-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pojazd', '0008_auto_20210716_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojazd',
            name='historia',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
