# Generated by Django 3.1.7 on 2021-07-17 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pojazd', '0009_auto_20210716_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazyn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('opis', models.TextField(max_length=10000)),
                ('zdjecie', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='pojazd',
            name='opony',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pojazd.magazyn'),
        ),
    ]
