# Generated by Django 3.1.7 on 2021-07-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pojazd', '0010_auto_20210717_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazyn',
            name='w_uzytku',
            field=models.BooleanField(default=0),
        ),
    ]
