# Generated by Django 3.1.7 on 2021-07-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pojazd', '0011_magazyn_w_uzytku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazyn',
            name='w_uzytku',
            field=models.CharField(max_length=100),
        ),
    ]
