# Generated by Django 3.1.7 on 2021-07-17 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pojazd', '0012_auto_20210717_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Felga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('sruby', models.CharField(max_length=200)),
                ('opis', models.TextField(max_length=10000)),
                ('zdjecie', models.FileField(blank=True, upload_to='')),
                ('w_uzytku', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Opona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('opis', models.TextField(max_length=10000)),
                ('zdjecie', models.FileField(blank=True, upload_to='')),
                ('w_uzytku', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='pojazd',
            name='felgi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pojazd.felga'),
        ),
        migrations.AlterField(
            model_name='pojazd',
            name='opony',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pojazd.opona'),
        ),
    ]
