# Generated by Django 3.1.7 on 2021-07-17 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pojazd', '0013_auto_20210717_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pojazd',
            name='felgi',
        ),
        migrations.RemoveField(
            model_name='pojazd',
            name='opony',
        ),
    ]
