# Generated by Django 3.1.7 on 2021-07-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pojazd', '0014_auto_20210717_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='felga',
            name='w_uzytku',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='magazyn',
            name='w_uzytku',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='opona',
            name='w_uzytku',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
