# Generated by Django 3.1.7 on 2021-07-17 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pojazd', '0015_auto_20210717_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='pojazd',
            name='felgi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pojazd.felga'),
        ),
        migrations.AddField(
            model_name='pojazd',
            name='opony',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pojazd.opona'),
        ),
    ]
