# Generated by Django 3.1.7 on 2021-07-18 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pojazd', '0016_auto_20210717_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='felga',
            name='opis',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='opona',
            name='opis',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='pojazd',
            name='kola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pojazd.pojazdkola'),
        ),
    ]
