# Generated by Django 3.1.7 on 2021-07-18 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pojazd', '0017_auto_20210718_0929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='felga',
            old_name='nazwa',
            new_name='nazwa_felgi',
        ),
        migrations.RenameField(
            model_name='opona',
            old_name='nazwa',
            new_name='nazwa_opony',
        ),
    ]
