# Generated by Django 3.1.7 on 2021-07-19 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pojazd', '0018_auto_20210718_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pojazd',
            name='felgi',
        ),
        migrations.RemoveField(
            model_name='pojazd',
            name='opony',
        ),
    ]
