# Generated by Django 3.1.7 on 2021-07-19 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pojazd', '0019_auto_20210719_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='pojazd',
            name='felgi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pojazd.felga'),
        ),
        migrations.AddField(
            model_name='pojazd',
            name='opony',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pojazd.opona'),
        ),
        migrations.AlterField(
            model_name='opona',
            name='opis',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='opona',
            name='w_uzytku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='opona',
            name='zdjecie',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
