# Generated by Django 3.1.7 on 2021-08-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pojazd', '0020_auto_20210719_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='felga',
            name='w_uzytku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
