# Generated by Django 3.1.7 on 2021-08-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pojazd', '0021_auto_20210805_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='felga',
            name='w_uzytku',
            field=models.CharField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='opona',
            name='w_uzytku',
            field=models.CharField(blank=True, default=0, max_length=100),
            preserve_default=False,
        ),
    ]
