# Generated by Django 3.1.7 on 2021-08-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pojazd', '0022_auto_20210806_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='felga',
            name='w_uzytku',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='opona',
            name='w_uzytku',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
