# Generated by Django 3.1.7 on 2021-08-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pojazd', '0023_auto_20210806_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='pojazd',
            name='przebieg',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
