# Generated by Django 3.1.7 on 2021-08-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pojazd', '0024_pojazd_przebieg'),
    ]

    operations = [
        migrations.AddField(
            model_name='pojazdhistoria',
            name='aktualny_przebieg',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
