# Generated by Django 3.1.7 on 2021-08-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pojazd', '0025_pojazdhistoria_aktualny_przebieg'),
    ]

    operations = [
        migrations.AddField(
            model_name='pojazd',
            name='zdjecie',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
