# Generated by Django 3.1.7 on 2021-08-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pojazd', '0026_pojazd_zdjecie'),
    ]

    operations = [
        migrations.CreateModel(
            name='PojazdHistoriaPrzebiegu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejestracja', models.CharField(max_length=100)),
                ('cel', models.CharField(max_length=300)),
                ('data', models.DateField()),
                ('opis', models.TextField(blank=True, max_length=10000)),
                ('przebieg_start', models.IntegerField()),
                ('przebieg_stop', models.IntegerField()),
            ],
        ),
    ]
