# Generated by Django 3.1.7 on 2021-08-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pojazd', '0027_pojazdhistoriaprzebiegu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pojazdhistoriaprzebiegu',
            old_name='opis',
            new_name='uwagi',
        ),
        migrations.AddField(
            model_name='pojazdhistoriaprzebiegu',
            name='kierowca',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
