# Generated by Django 3.1.7 on 2021-08-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pojazd', '0028_auto_20210811_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='pojazdhistoriaprzebiegu',
            name='do',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pojazdhistoriaprzebiegu',
            name='z',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
