# Generated by Django 3.1.7 on 2021-08-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pojazd', '0029_auto_20210811_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojazd',
            name='zdjecie',
            field=models.FileField(blank=True, upload_to='documents/%Y/%m/%d'),
        ),
    ]
