# Generated by Django 3.1.7 on 2021-08-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pojazd', '0030_auto_20210814_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pojazd',
            options={'permissions': (('can_add_vehicles', 'Doadj nowy pojazd'), ('can_add_history  ', 'Doadj nowy wpis'))},
        ),
        migrations.AlterField(
            model_name='pojazd',
            name='zdjecie',
            field=models.FileField(blank=True, upload_to='img/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='pojazdhistoria',
            name='zdjecie',
            field=models.FileField(blank=True, upload_to='img/historia/%Y/%m/%d'),
        ),
    ]
