# Generated by Django 3.1.7 on 2021-08-18 12:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Pojazd', '0031_auto_20210817_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='felga',
            name='data_dodania',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='felga',
            name='dodal',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opona',
            name='data_dodania',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='opona',
            name='dodal',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pojazd',
            name='data_dodania',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pojazd',
            name='dodal',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pojazdhistoria',
            name='data_dodania',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pojazdhistoria',
            name='dodal',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pojazdhistoriaprzebiegu',
            name='data_dodania',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pojazdhistoriaprzebiegu',
            name='dodal',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
