# Generated by Django 3.1.7 on 2021-08-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pojazd', '0032_auto_20210818_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opona',
            name='data_dodania',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
