# Generated by Django 3.1.7 on 2021-08-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pojazd', '0033_auto_20210818_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='felga',
            name='data_dodania',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pojazd',
            name='data_dodania',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pojazdhistoria',
            name='data_dodania',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pojazdhistoriaprzebiegu',
            name='data_dodania',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
