# Generated by Django 3.1.7 on 2021-08-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pojazd', '0034_auto_20210818_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='pojazd',
            name='przypisany',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
