# Generated by Django 3.1.7 on 2021-08-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pojazd', '0035_pojazd_przypisany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojazd',
            name='data_dodania',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
