# Generated by Django 3.1.7 on 2021-08-25 09:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Pojazd', '0036_auto_20210820_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='pojazd',
            name='n_przeglad',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pojazd',
            name='nr_polisy',
            field=models.CharField(default='1111000011111', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pojazd',
            name='oc_do',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
