# Generated by Django 3.1.7 on 2021-08-26 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pojazd', '0037_auto_20210825_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pojazd',
            name='kola',
        ),
        migrations.DeleteModel(
            name='PojazdKola',
        ),
    ]
