# Generated by Django 3.1.7 on 2021-08-31 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pojazd', '0038_auto_20210826_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='opona',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='opona',
            name='producent',
            field=models.CharField(default='Hankock', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opona',
            name='rok_produkcji',
            field=models.IntegerField(default='2020', verbose_name=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opona',
            name='rozmiar',
            field=models.CharField(default='215/50/r17', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opona',
            name='sezon',
            field=models.CharField(default='Lato', max_length=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='opona',
            name='zdjecie',
            field=models.FileField(blank=True, default=1, upload_to='img/opony/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pojazd',
            name='przypisany',
            field=models.CharField(default='1', max_length=300),
        ),
        migrations.AlterField(
            model_name='pojazd',
            name='zdjecie',
            field=models.FileField(blank=True, null=True, upload_to='img/pojazdy/%Y/%m/%d'),
        ),
    ]
