# Generated by Django 3.1.7 on 2021-09-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pojazd', '0040_auto_20210831_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='pojazdhistoria',
            name='rachunek',
            field=models.FileField(blank=True, upload_to='rachunki/historia/%Y/%m/%d'),
        ),
    ]
