# Generated by Django 3.1.7 on 2021-11-05 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pojazd', '0041_pojazdhistoria_rachunek'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pojazdtemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=300)),
                ('rok_produkcji', models.IntegerField()),
                ('silnik', models.CharField(max_length=100)),
                ('rejestracja', models.CharField(max_length=100, unique=True)),
                ('kolor', models.CharField(max_length=100)),
                ('data_zakupu', models.DateField()),
                ('data_sprzedazy', models.DateField(blank=True, null=True)),
                ('historia', models.IntegerField(blank=True, null=True)),
                ('przebieg', models.IntegerField()),
                ('zdjecie', models.FileField(blank=True, upload_to='img/pojazdy/%Y/%m/%d')),
                ('dodal', models.CharField(max_length=200)),
                ('data_dodania', models.DateTimeField(auto_now_add=True, null=True)),
                ('przypisany', models.CharField(default='1', max_length=300)),
                ('n_przeglad', models.DateField()),
                ('oc_do', models.DateField()),
                ('nr_polisy', models.CharField(max_length=40)),
                ('felgi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pojazd.felga')),
                ('opony', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pojazd.opona')),
            ],
            options={
                'permissions': (('can_add_vehicles', 'Doadj nowy pojazd'), ('can_add_history  ', 'Doadj nowy wpis')),
            },
        ),
    ]
