# Generated by Django 4.2.16 on 2026-06-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pojazd', '0042_pojazdtemp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opona',
            name='rok_produkcji',
            field=models.IntegerField(),
        ),
    ]
